# Generated by Django 4.2 on 2023-05-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_brand_name', models.CharField(default='', max_length=200, null=True)),
                ('p_quantity', models.CharField(default='', max_length=200, null=True)),
                ('packing_size', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
