# Generated by Django 4.2 on 2023-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='bundle_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='p_standard',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='p_subject',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
