# Generated by Django 4.2 on 2023-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0002_packing_bundle_size_packing_p_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='pack_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
