# Generated by Django 4.2 on 2023-06-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0003_packing_pack_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='pack_size',
        ),
    ]
