# Generated by Django 4.2.4 on 2023-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0004_remove_packing_pack_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bittipacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitti_book_code', models.CharField(default='', max_length=200, null=True)),
                ('bitti_medium', models.CharField(default='', max_length=200, null=True)),
                ('bitti_brand_name', models.CharField(default='', max_length=200, null=True)),
                ('bitti_quantity', models.CharField(default='', max_length=200, null=True)),
                ('bitti_packing_size', models.CharField(default='', max_length=200, null=True)),
                ('bitti_standard', models.CharField(default='', max_length=200, null=True)),
                ('bitti_subject', models.CharField(default='', max_length=200, null=True)),
                ('bitti_bundle_size', models.CharField(default='', max_length=200, null=True)),
                ('bitti_date', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='packing',
            name='p_date',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
