# Generated by Django 4.2.4 on 2023-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0006_packing_p_book_code_packing_p_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bittipacking',
            name='bitti_pack_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bittipacking',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bittipacking',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='shrink_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packing',
            name='shrink_pack_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='to_shrink',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='tra_from_shrink',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='transfer_pending',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
