# Generated by Django 4.2.4 on 2023-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0007_bittipacking_bitti_pack_size_bittipacking_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='pack_quantity',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
