# Generated by Django 4.1.3 on 2023-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=200, null=True)),
                ('vender_name', models.CharField(default='', max_length=200, null=True)),
                ('total_quantity', models.CharField(default='', max_length=200, null=True)),
                ('total_printing_received', models.CharField(default='', max_length=200, null=True)),
                ('wastage_form', models.CharField(default='', max_length=200, null=True)),
                ('printing_added_on', models.DateTimeField(null='True')),
            ],
        ),
    ]
