# Generated by Django 4.1.3 on 2023-02-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_printing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gathering',
        ),
    ]
