# Generated by Django 4.1.3 on 2023-02-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_delete_gathering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='printing',
        ),
    ]
