# Generated by Django 5.0 on 2024-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_alter_manual_binding_brand_name44_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_binding',
            name='material_center',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
