# Generated by Django 5.0 on 2024-02-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_manual_binding_material_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_printing_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vender_transfer_to', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vender_transfer_from', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_voucher_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_subject', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no11', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty11', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_form_no12', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_transfer_qty12', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
