# Generated by Django 5.0 on 2024-02-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_cover_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_topi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vender_transfer_to', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vender_transfer_from', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('topi_transfer_voucher_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('topi_transfer_subject1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('topi_transfer_qty1', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
