from django.db import models
# Create your models here.

class Manual_binding(models.Model):
    material_center =models.CharField(max_length=200,default='', null=True)
    order_id =models.CharField(max_length=200,default='', null=True)
    brand_name1=models.CharField(max_length=200,default='', null=True, blank=True)
    class_name1=models.CharField(max_length=200,default='', null=True,blank=True)
    medium1=models.CharField(max_length=200,default='', null=True,blank=True)
    subject1=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity1=models.CharField(max_length=200,default='', null=True,blank=True)
    striching1=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting1=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting1=models.CharField(max_length=200,default='', null=True,blank=True)
    rim1=models.CharField(max_length=200,default='', null=True,blank=True)
    pages1=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name2=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name2=models.CharField(max_length=200,default='', null=True,blank=True)
    medium2=models.CharField(max_length=200,default='', null=True,blank=True)
    subject2=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity2=models.CharField(max_length=200,default='', null=True,blank=True)
    striching2=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting2=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting2=models.CharField(max_length=200,default='', null=True,blank=True)
    rim2=models.CharField(max_length=200,default='', null=True,blank=True)
    pages2=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name3=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name3=models.CharField(max_length=200,default='', null=True,blank=True)
    medium3=models.CharField(max_length=200,default='', null=True,blank=True)
    subject3=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity3=models.CharField(max_length=200,default='', null=True,blank=True)
    striching3=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting3=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting3=models.CharField(max_length=200,default='', null=True,blank=True)
    rim3=models.CharField(max_length=200,default='', null=True,blank=True)
    pages3=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name4=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name4=models.CharField(max_length=200,default='', null=True,blank=True)
    medium4=models.CharField(max_length=200,default='', null=True,blank=True)
    subject4=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity4=models.CharField(max_length=200,default='', null=True,blank=True)
    striching4=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting4=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting4=models.CharField(max_length=200,default='', null=True,blank=True)
    rim4=models.CharField(max_length=200,default='', null=True,blank=True)
    pages4=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name5=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name5=models.CharField(max_length=200,default='', null=True,blank=True)
    medium5=models.CharField(max_length=200,default='', null=True,blank=True)
    subject5=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity5=models.CharField(max_length=200,default='', null=True,blank=True)
    striching5=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting5=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting5=models.CharField(max_length=200,default='', null=True,blank=True)
    rim5=models.CharField(max_length=200,default='', null=True,blank=True)
    pages5=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name6=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name6=models.CharField(max_length=200,default='', null=True,blank=True)
    medium6=models.CharField(max_length=200,default='', null=True,blank=True)
    subject6=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity6=models.CharField(max_length=200,default='', null=True,blank=True)
    striching6=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting6=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting6=models.CharField(max_length=200,default='', null=True,blank=True)
    rim6=models.CharField(max_length=200,default='', null=True,blank=True)
    pages6=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name7=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name7=models.CharField(max_length=200,default='', null=True,blank=True)
    medium7=models.CharField(max_length=200,default='', null=True,blank=True)
    subject7=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity7=models.CharField(max_length=200,default='', null=True,blank=True)
    striching7=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting7=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting7=models.CharField(max_length=200,default='', null=True,blank=True)
    rim7=models.CharField(max_length=200,default='', null=True,blank=True)
    pages7=models.CharField(max_length=200,default='', null=True,blank=True)

    class_name8=models.CharField(max_length=200,default='', null=True,blank=True)
    brand_name8=models.CharField(max_length=200,default='', null=True,blank=True)
    medium8=models.CharField(max_length=200,default='', null=True,blank=True)
    subject8=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity8=models.CharField(max_length=200,default='', null=True,blank=True)
    striching8=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting8=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting8=models.CharField(max_length=200,default='', null=True,blank=True)
    rim8=models.CharField(max_length=200,default='', null=True,blank=True)
    pages8=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name9=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name9=models.CharField(max_length=200,default='', null=True,blank=True)
    medium9=models.CharField(max_length=200,default='', null=True,blank=True)
    subject9=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity9=models.CharField(max_length=200,default='', null=True,blank=True)
    striching9=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting9=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting9=models.CharField(max_length=200,default='', null=True,blank=True)
    rim9=models.CharField(max_length=200,default='', null=True,blank=True)
    pages9=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name10=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name10=models.CharField(max_length=200,default='', null=True,blank=True)
    medium10=models.CharField(max_length=200,default='', null=True,blank=True)
    subject10=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity10=models.CharField(max_length=200,default='', null=True,blank=True)
    striching10=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting10=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting10=models.CharField(max_length=200,default='', null=True,blank=True)
    rim10=models.CharField(max_length=200,default='', null=True,blank=True)
    pages10=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name11=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name11=models.CharField(max_length=200,default='', null=True,blank=True)
    medium11=models.CharField(max_length=200,default='', null=True,blank=True)
    subject11=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity11=models.CharField(max_length=200,default='', null=True,blank=True)
    striching11=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting11=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting11=models.CharField(max_length=200,default='', null=True,blank=True)
    rim11=models.CharField(max_length=200,default='', null=True,blank=True)
    pages11=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name12=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name12=models.CharField(max_length=200,default='', null=True,blank=True)
    medium12=models.CharField(max_length=200,default='', null=True,blank=True)
    subject12=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity12=models.CharField(max_length=200,default='', null=True,blank=True)
    striching12=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting12=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting12=models.CharField(max_length=200,default='', null=True,blank=True)
    rim12=models.CharField(max_length=200,default='', null=True,blank=True)
    pages12=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name13=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name13=models.CharField(max_length=200,default='', null=True,blank=True)
    medium13=models.CharField(max_length=200,default='', null=True,blank=True)
    subject13=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity13=models.CharField(max_length=200,default='', null=True,blank=True)
    striching13=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting13=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting13=models.CharField(max_length=200,default='', null=True,blank=True)
    rim13=models.CharField(max_length=200,default='', null=True,blank=True)
    pages13=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name14=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name14=models.CharField(max_length=200,default='', null=True,blank=True)
    medium14=models.CharField(max_length=200,default='', null=True,blank=True)
    subject14=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity14=models.CharField(max_length=200,default='', null=True,blank=True)
    striching14=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting14=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting14=models.CharField(max_length=200,default='', null=True,blank=True)
    rim14=models.CharField(max_length=200,default='', null=True,blank=True)
    pages14=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name15=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name15=models.CharField(max_length=200,default='', null=True,blank=True)
    medium15=models.CharField(max_length=200,default='', null=True,blank=True)
    subject15=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity15=models.CharField(max_length=200,default='', null=True,blank=True)
    striching15=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting15=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting15=models.CharField(max_length=200,default='', null=True,blank=True)
    rim15=models.CharField(max_length=200,default='', null=True,blank=True)
    pages15=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name16=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name16=models.CharField(max_length=200,default='', null=True,blank=True)
    medium16=models.CharField(max_length=200,default='', null=True,blank=True)
    subject16=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity16=models.CharField(max_length=200,default='', null=True,blank=True)
    striching16=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting16=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting16=models.CharField(max_length=200,default='', null=True,blank=True)
    rim16=models.CharField(max_length=200,default='', null=True,blank=True)
    pages16=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name17=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name17=models.CharField(max_length=200,default='', null=True,blank=True)
    medium17=models.CharField(max_length=200,default='', null=True,blank=True)
    subject17=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity17=models.CharField(max_length=200,default='', null=True,blank=True)
    striching17=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting17=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting17=models.CharField(max_length=200,default='', null=True,blank=True)
    rim17=models.CharField(max_length=200,default='', null=True,blank=True)
    pages17=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name17=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name17=models.CharField(max_length=200,default='', null=True,blank=True)
    medium17=models.CharField(max_length=200,default='', null=True,blank=True)
    subject17=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity17=models.CharField(max_length=200,default='', null=True,blank=True)
    striching17=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting17=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting17=models.CharField(max_length=200,default='', null=True,blank=True)
    rim17=models.CharField(max_length=200,default='', null=True,blank=True)
    pages17=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name18=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name18=models.CharField(max_length=200,default='', null=True,blank=True)
    medium18=models.CharField(max_length=200,default='', null=True,blank=True)
    subject18=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity18=models.CharField(max_length=200,default='', null=True,blank=True)
    striching18=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting18=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting18=models.CharField(max_length=200,default='', null=True,blank=True)
    rim18=models.CharField(max_length=200,default='', null=True,blank=True)
    pages18=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name19=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name19=models.CharField(max_length=200,default='', null=True,blank=True)
    medium19=models.CharField(max_length=200,default='', null=True,blank=True)
    subject19=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity19=models.CharField(max_length=200,default='', null=True,blank=True)
    striching19=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting19=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting19=models.CharField(max_length=200,default='', null=True,blank=True)
    rim19=models.CharField(max_length=200,default='', null=True,blank=True)
    pages19=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name20=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name20=models.CharField(max_length=200,default='', null=True,blank=True)
    medium20=models.CharField(max_length=200,default='', null=True,blank=True)
    subject20=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity20=models.CharField(max_length=200,default='', null=True,blank=True)
    striching20=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting20=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting20=models.CharField(max_length=200,default='', null=True,blank=True)
    rim20=models.CharField(max_length=200,default='', null=True,blank=True)
    pages20=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name21=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name21=models.CharField(max_length=200,default='', null=True,blank=True)
    medium21=models.CharField(max_length=200,default='', null=True,blank=True)
    subject21=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity21=models.CharField(max_length=200,default='', null=True,blank=True)
    striching21=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting21=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting21=models.CharField(max_length=200,default='', null=True,blank=True)
    rim21=models.CharField(max_length=200,default='', null=True,blank=True)
    pages21=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name22=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name22=models.CharField(max_length=200,default='', null=True,blank=True)
    medium22=models.CharField(max_length=200,default='', null=True,blank=True)
    subject22=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity22=models.CharField(max_length=200,default='', null=True,blank=True)
    striching22=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting22=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting22=models.CharField(max_length=200,default='', null=True,blank=True)
    rim22=models.CharField(max_length=200,default='', null=True,blank=True)
    pages22=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name23=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name23=models.CharField(max_length=200,default='', null=True,blank=True)
    medium23=models.CharField(max_length=200,default='', null=True,blank=True)
    subject23=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity23=models.CharField(max_length=200,default='', null=True,blank=True)
    striching23=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting23=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting23=models.CharField(max_length=200,default='', null=True,blank=True)
    rim23=models.CharField(max_length=200,default='', null=True,blank=True)
    pages23=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name24=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name24=models.CharField(max_length=200,default='', null=True,blank=True)
    medium24=models.CharField(max_length=200,default='', null=True,blank=True)
    subject24=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity24=models.CharField(max_length=200,default='', null=True,blank=True)
    striching24=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting24=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting24=models.CharField(max_length=200,default='', null=True,blank=True)
    rim24=models.CharField(max_length=200,default='', null=True,blank=True)
    pages24=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name25=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name25=models.CharField(max_length=200,default='', null=True,blank=True)
    medium25=models.CharField(max_length=200,default='', null=True,blank=True)
    subject25=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity25=models.CharField(max_length=200,default='', null=True,blank=True)
    striching25=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting25=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting25=models.CharField(max_length=200,default='', null=True,blank=True)
    rim25=models.CharField(max_length=200,default='', null=True,blank=True)
    pages25=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name26=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name26=models.CharField(max_length=200,default='', null=True,blank=True)
    medium26=models.CharField(max_length=200,default='', null=True,blank=True)
    subject26=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity26=models.CharField(max_length=200,default='', null=True,blank=True)
    striching26=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting26=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting26=models.CharField(max_length=200,default='', null=True,blank=True)
    rim26=models.CharField(max_length=200,default='', null=True,blank=True)
    pages26=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name27=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name27=models.CharField(max_length=200,default='', null=True,blank=True)
    medium27=models.CharField(max_length=200,default='', null=True,blank=True)
    subject27=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity27=models.CharField(max_length=200,default='', null=True,blank=True)
    striching27=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting27=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting27=models.CharField(max_length=200,default='', null=True,blank=True)
    rim27=models.CharField(max_length=200,default='', null=True,blank=True)
    pages27=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name28=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name28=models.CharField(max_length=200,default='', null=True,blank=True)
    medium28=models.CharField(max_length=200,default='', null=True,blank=True)
    subject28=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity28=models.CharField(max_length=200,default='', null=True,blank=True)
    striching28=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting28=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting28=models.CharField(max_length=200,default='', null=True,blank=True)
    rim28=models.CharField(max_length=200,default='', null=True,blank=True)
    pages28=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name29=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name29=models.CharField(max_length=200,default='', null=True,blank=True)
    medium29=models.CharField(max_length=200,default='', null=True,blank=True)
    subject29=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity29=models.CharField(max_length=200,default='', null=True,blank=True)
    striching29=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting29=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting29=models.CharField(max_length=200,default='', null=True,blank=True)
    rim29=models.CharField(max_length=200,default='', null=True,blank=True)
    pages29=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name30=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name30=models.CharField(max_length=200,default='', null=True,blank=True)
    medium30=models.CharField(max_length=200,default='', null=True,blank=True)
    subject30=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity30=models.CharField(max_length=200,default='', null=True,blank=True)
    striching30=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting30=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting30=models.CharField(max_length=200,default='', null=True,blank=True)
    rim30=models.CharField(max_length=200,default='', null=True,blank=True)
    pages30=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name31=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name31=models.CharField(max_length=200,default='', null=True,blank=True)
    medium31=models.CharField(max_length=200,default='', null=True,blank=True)
    subject31=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity31=models.CharField(max_length=200,default='', null=True,blank=True)
    striching31=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting31=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting31=models.CharField(max_length=200,default='', null=True,blank=True)
    rim31=models.CharField(max_length=200,default='', null=True,blank=True)
    pages31=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name32=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name32=models.CharField(max_length=200,default='', null=True,blank=True)
    medium32=models.CharField(max_length=200,default='', null=True,blank=True)
    subject32=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity32=models.CharField(max_length=200,default='', null=True,blank=True)
    striching32=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting32=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting32=models.CharField(max_length=200,default='', null=True,blank=True)
    rim32=models.CharField(max_length=200,default='', null=True,blank=True)
    pages32=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name33=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name33=models.CharField(max_length=200,default='', null=True,blank=True)
    medium33=models.CharField(max_length=200,default='', null=True,blank=True)
    subject33=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity33=models.CharField(max_length=200,default='', null=True,blank=True)
    striching33=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting33=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting33=models.CharField(max_length=200,default='', null=True,blank=True)
    rim33=models.CharField(max_length=200,default='', null=True,blank=True)
    pages33=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name34=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name34=models.CharField(max_length=200,default='', null=True,blank=True)
    medium34=models.CharField(max_length=200,default='', null=True,blank=True)
    subject34=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity34=models.CharField(max_length=200,default='', null=True,blank=True)
    striching34=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting34=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting34=models.CharField(max_length=200,default='', null=True,blank=True)
    rim34=models.CharField(max_length=200,default='', null=True,blank=True)
    pages34=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name35=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name35=models.CharField(max_length=200,default='', null=True,blank=True)
    medium35=models.CharField(max_length=200,default='', null=True,blank=True)
    subject35=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity35=models.CharField(max_length=200,default='', null=True,blank=True)
    striching35=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting35=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting35=models.CharField(max_length=200,default='', null=True,blank=True)
    rim35=models.CharField(max_length=200,default='', null=True,blank=True)
    pages35=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name36=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name36=models.CharField(max_length=200,default='', null=True,blank=True)
    medium36=models.CharField(max_length=200,default='', null=True,blank=True)
    subject36=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity36=models.CharField(max_length=200,default='', null=True,blank=True)
    striching36=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting36=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting36=models.CharField(max_length=200,default='', null=True,blank=True)
    rim36=models.CharField(max_length=200,default='', null=True,blank=True)
    pages36=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name37=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name37=models.CharField(max_length=200,default='', null=True,blank=True)
    medium37=models.CharField(max_length=200,default='', null=True,blank=True)
    subject37=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity37=models.CharField(max_length=200,default='', null=True,blank=True)
    striching37=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting37=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting37=models.CharField(max_length=200,default='', null=True,blank=True)
    rim37=models.CharField(max_length=200,default='', null=True,blank=True)
    pages37=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name38=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name38=models.CharField(max_length=200,default='', null=True,blank=True)
    medium38=models.CharField(max_length=200,default='', null=True,blank=True)
    subject38=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity38=models.CharField(max_length=200,default='', null=True,blank=True)
    striching38=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting38=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting38=models.CharField(max_length=200,default='', null=True,blank=True)
    rim38=models.CharField(max_length=200,default='', null=True,blank=True)
    pages38=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name39=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name39=models.CharField(max_length=200,default='', null=True,blank=True)
    medium39=models.CharField(max_length=200,default='', null=True,blank=True)
    subject39=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity39=models.CharField(max_length=200,default='', null=True,blank=True)
    striching39=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting39=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting39=models.CharField(max_length=200,default='', null=True,blank=True)
    rim39=models.CharField(max_length=200,default='', null=True,blank=True)
    pages39=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name40=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name40=models.CharField(max_length=200,default='', null=True,blank=True)
    medium40=models.CharField(max_length=200,default='', null=True,blank=True)
    subject40=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity40=models.CharField(max_length=200,default='', null=True,blank=True)
    striching40=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting40=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting40=models.CharField(max_length=200,default='', null=True,blank=True)
    rim40=models.CharField(max_length=200,default='', null=True,blank=True)
    pages40=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name41=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name41=models.CharField(max_length=200,default='', null=True,blank=True)
    medium41=models.CharField(max_length=200,default='', null=True,blank=True)
    subject41=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity41=models.CharField(max_length=200,default='', null=True,blank=True)
    striching41=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting41=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting41=models.CharField(max_length=200,default='', null=True,blank=True)
    rim41=models.CharField(max_length=200,default='', null=True,blank=True)
    pages41=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name42=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name42=models.CharField(max_length=200,default='', null=True,blank=True)
    medium42=models.CharField(max_length=200,default='', null=True,blank=True)
    subject42=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity42=models.CharField(max_length=200,default='', null=True,blank=True)
    striching42=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting42=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting42=models.CharField(max_length=200,default='', null=True,blank=True)
    rim42=models.CharField(max_length=200,default='', null=True,blank=True)
    pages42=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name43=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name43=models.CharField(max_length=200,default='', null=True,blank=True)
    medium43=models.CharField(max_length=200,default='', null=True,blank=True)
    subject43=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity43=models.CharField(max_length=200,default='', null=True,blank=True)
    striching43=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting43=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting43=models.CharField(max_length=200,default='', null=True,blank=True)
    rim43=models.CharField(max_length=200,default='', null=True,blank=True)
    pages43=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name44=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name44=models.CharField(max_length=200,default='', null=True,blank=True)
    medium44=models.CharField(max_length=200,default='', null=True,blank=True)
    subject44=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity44=models.CharField(max_length=200,default='', null=True,blank=True)
    striching44=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting44=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting44=models.CharField(max_length=200,default='', null=True,blank=True)
    rim44=models.CharField(max_length=200,default='', null=True,blank=True)
    pages44=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name45=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name45=models.CharField(max_length=200,default='', null=True,blank=True)
    medium45=models.CharField(max_length=200,default='', null=True,blank=True)
    subject45=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity45=models.CharField(max_length=200,default='', null=True,blank=True)
    striching45=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting45=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting45=models.CharField(max_length=200,default='', null=True,blank=True)
    rim45=models.CharField(max_length=200,default='', null=True,blank=True)
    pages45=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name46=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name46=models.CharField(max_length=200,default='', null=True,blank=True)
    medium46=models.CharField(max_length=200,default='', null=True,blank=True)
    subject46=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity46=models.CharField(max_length=200,default='', null=True,blank=True)
    striching46=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting46=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting46=models.CharField(max_length=200,default='', null=True,blank=True)
    rim46=models.CharField(max_length=200,default='', null=True,blank=True)
    pages46=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name47=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name47=models.CharField(max_length=200,default='', null=True,blank=True)
    medium47=models.CharField(max_length=200,default='', null=True,blank=True)
    subject47=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity47=models.CharField(max_length=200,default='', null=True,blank=True)
    striching47=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting47=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting47=models.CharField(max_length=200,default='', null=True,blank=True)
    rim47=models.CharField(max_length=200,default='', null=True,blank=True)
    pages47=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name48=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name48=models.CharField(max_length=200,default='', null=True,blank=True)
    medium48=models.CharField(max_length=200,default='', null=True,blank=True)
    subject48=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity48=models.CharField(max_length=200,default='', null=True,blank=True)
    striching48=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting48=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting48=models.CharField(max_length=200,default='', null=True,blank=True)
    rim48=models.CharField(max_length=200,default='', null=True,blank=True)
    pages48=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name49=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name49=models.CharField(max_length=200,default='', null=True,blank=True)
    medium49=models.CharField(max_length=200,default='', null=True,blank=True)
    subject49=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity49=models.CharField(max_length=200,default='', null=True,blank=True)
    striching49=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting49=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting49=models.CharField(max_length=200,default='', null=True,blank=True)
    rim49=models.CharField(max_length=200,default='', null=True,blank=True)
    pages49=models.CharField(max_length=200,default='', null=True,blank=True)

    brand_name50=models.CharField(max_length=200,default='', null=True,blank=True)
    class_name50=models.CharField(max_length=200,default='', null=True,blank=True)
    medium50=models.CharField(max_length=200,default='', null=True,blank=True)
    subject50=models.CharField(max_length=200,default='', null=True,blank=True)
    quantity50=models.CharField(max_length=200,default='', null=True,blank=True)
    striching50=models.CharField(max_length=200,default='', null=True,blank=True)
    pasting50=models.CharField(max_length=200,default='', null=True,blank=True)
    cutting50=models.CharField(max_length=200,default='', null=True,blank=True)
    rim50=models.CharField(max_length=200,default='', null=True,blank=True)
    pages50=models.CharField(max_length=200,default='', null=True,blank=True)



    def __str__(self):
        return self.order_id
    



class transfer_printing_module(models.Model):
    date=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_to=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_from=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_voucher_no=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_subject=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no1=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty1=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no2=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty2=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no3=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty3=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no4=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty4=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no5=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty5=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no6=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty6=models.CharField(max_length=200,default='', null=True,blank=True)

    print_transfer_form_no7=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty7=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no8=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty8=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no9=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty9=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no10=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty10=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no11=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty11=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_form_no12=models.CharField(max_length=200,default='', null=True,blank=True)
    print_transfer_qty12=models.CharField(max_length=200,default='', null=True,blank=True)
    


class cover_transfer(models.Model):
    date=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_to=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_from=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_voucher_no=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_subject1=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_qty1=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_unit1=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_subject2=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_qty2=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_unit2=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_subject3=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_qty3=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_unit3=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_subject4=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_qty4=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_unit4=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_subject5=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_qty5=models.CharField(max_length=200,default='', null=True,blank=True)
    cover_transfer_unit5=models.CharField(max_length=200,default='', null=True,blank=True)



class transfer_topi(models.Model):
    date=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_to=models.CharField(max_length=200,default='', null=True,blank=True)
    vender_transfer_from=models.CharField(max_length=200,default='', null=True,blank=True)
    topi_transfer_voucher_no=models.CharField(max_length=200,default='', null=True,blank=True)
    topi_transfer_subject1=models.CharField(max_length=200,default='', null=True,blank=True)
    topi_transfer_qty1=models.CharField(max_length=200,default='', null=True,blank=True)