# Generated by Django 4.1.2 on 2023-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='print_approved',
            field=models.BooleanField(default=False),
        ),
    ]
