# Generated by Django 4.1.2 on 2023-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_orders_binding_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
