# Generated by Django 4.1.2 on 2023-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_orders_complete_book_gathered_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='complete_book_gathered_9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
