# Generated by Django 4.1.2 on 2023-08-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_orders_complete_book_gathered_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_10',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_4',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_5',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_6',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_7',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_8',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='complete_book_gathered_9',
        ),
    ]
