# Generated by Django 4.2.4 on 2023-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_orders_order_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='code_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
