# Generated by Django 4.2.4 on 2023-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_orders_code_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='code_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
