# Generated by Django 4.2.4 on 2023-09-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_orders_code_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='code_4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
