# Generated by Django 4.2.4 on 2023-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0013_orders_code_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='company_name1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
