# Generated by Django 4.2.4 on 2023-10-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_orders_company_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingorder',
            name='company_binding',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
