# Generated by Django 4.2.4 on 2023-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_bindingorder_company_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rate1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
