# Generated by Django 4.2.4 on 2023-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_bindingorder_brand_1_bindingorder_brand_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingorder',
            name='brand_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
