# Generated by Django 4.2.4 on 2023-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_bindingorder_brand_10_bindingorder_brand_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingorder',
            name='brand_26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='brand_50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='class_50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='code_50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='midium_50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
