# Generated by Django 4.2.4 on 2023-11-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_bindingorder_brand_26_bindingorder_brand_27_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='b_amount9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bindingorder',
            name='binding_total_amount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
