# Generated by Django 4.2.4 on 2023-12-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0021_bill_sundry'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_voucher_date', models.CharField(max_length=100)),
                ('pr_voucher_series', models.CharField(max_length=100)),
                ('pr_voucher_no', models.CharField(max_length=100)),
                ('pr_voucher_bom_name', models.IntegerField()),
                ('pr_voucher_narration', models.CharField(max_length=50)),
                ('pr_voucher_item_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('pr_voucher_qty_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_voucher_unit_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_voucher_price_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_voucher_amount_1', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_data', models.JSONField(blank=True, null=True)),
                ('dynamic_data1', models.JSONField(blank=True, null=True)),
                ('consumed_voucher_item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('consumed_voucher_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_price', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_item_name_1', models.CharField(blank=True, max_length=50, null=True)),
                ('consumed_voucher_qty_1', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_unit_1', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_price_1', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_voucher_amount_1', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
