# Generated by Django 4.2.4 on 2023-12-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0022_product_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=100)),
                ('bom_alias', models.CharField(max_length=100)),
                ('bom_item_produce', models.CharField(max_length=100)),
                ('bom_quantity', models.IntegerField()),
                ('bom_unit', models.CharField(max_length=50)),
                ('bom_unit1', models.CharField(max_length=50)),
                ('bom_exp', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_item_generated', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_item_consumed_1', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_generated_unit_1', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_generated_qty_1', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_generated_item_1', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_data', models.JSONField(blank=True, null=True)),
                ('bom_generated_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_generated_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('bom_generated_item', models.CharField(blank=True, max_length=100, null=True)),
                ('dynamic_data1', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
