# Generated by Django 5.0 on 2023-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0023_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='bom_item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_item_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_qty_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_unit_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
