# Generated by Django 5.0 on 2023-12-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0025_sale_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_sundry',
            name='cost_good_material_issue',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill_sundry',
            name='material_issue',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill_sundry',
            name='print_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
