# Generated by Django 5.0 on 2024-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0026_bill_sundry_cost_good_material_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rate10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='rate9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
