# Generated by Django 5.0 on 2024-01-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0027_orders_rate10_orders_rate11_orders_rate12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingorder',
            name='b_amount',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
