# Generated by Django 5.0 on 2024-01-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0028_alter_bindingorder_b_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pform_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
