# Generated by Django 5.0 on 2024-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0029_orders_pform_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_17',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_18',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_19',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_20',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_21',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_23',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_24',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_25',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_26',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_27',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_28',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_29',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_30',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_31',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_32',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_34',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_35',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_36',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_37',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_38',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_39',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_40',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_41',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_42',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_43',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_44',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_45',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_46',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_47',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_48',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_49',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_50',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount_9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
