# Generated by Django 5.0 on 2024-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0031_bom_bom_quantity1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='bom_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
