# Generated by Django 5.0 on 2024-02-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0035_remove_orders_gathering_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='bill_amount_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_amount_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_amount_3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_amount_4',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_amount_5',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_sundries_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_sundries_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_sundries_3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_sundries_4',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='bill_sundries_5',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='narration_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='narration_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='narration_3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='narration_4',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='narration_5',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='percent_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='percent_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='percent_3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='percent_4',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='percent_5',
        ),
    ]
