from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(brands)
admin.site.register(Subbrand)
admin.site.register(classes)
admin.site.register(books)
admin.site.register(Company)
admin.site.register(Bindingvender)
admin.site.register(Cuttingvender)
admin.site.register(Packingvender)
admin.site.register(Gatheringvender)
admin.site.register(Covervender)
admin.site.register(mediums)
admin.site.register(forms)
admin.site.register(venders)
admin.site.register(material_centre)
admin.site.register(Group)
admin.site.register(Distributors)
admin.site.register(Gathering)
admin.site.register(Binding)
admin.site.register(Cuttting)
admin.site.register(printing)
admin.site.register(Manual)
admin.site.register(vouchers)
admin.site.register(Pasting)
admin.site.register(Manual_cutting)
admin.site.register(Cover_Printing)
admin.site.register(Subject)
admin.site.register(Cover_order)
admin.site.register(Main_group)
admin.site.register(Item_creation)
admin.site.register(database)
admin.site.register(transaction_operation)
admin.site.register(Binder_ledger)
admin.site.register(Gather_ledger)
admin.site.register(Paster_ledger)
admin.site.register(Stitcher_ledger)
admin.site.register(Machine_ledger)
admin.site.register(Cutter_ledger)
admin.site.register(Packer_ledger)
admin.site.register(General_ledger)
admin.site.register(Customer_ledger)
admin.site.register(cover_scrap_voucher)
admin.site.register(other_vouchers)
admin.site.register(District)
admin.site.register(Category)
admin.site.register(product_by)
admin.site.register(Form_Printing)
admin.site.register(Cover_rawmaterial)
admin.site.register(master_unit)
admin.site.register(conversion_unit)
admin.site.register(item_master)
admin.site.register(District1)
admin.site.register(Tour_group)

