# Generated by Django 4.2.4 on 2023-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user_is_binding_user_is_cutting_user_is_gathering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_roles', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
