# Generated by Django 4.2.4 on 2023-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_lamination', models.CharField(default='', max_length=200, null=True)),
                ('quantity_lamination', models.CharField(default='', max_length=200, null=True)),
                ('unit_lamination', models.CharField(default='', max_length=200, null=True)),
                ('date_lamination', models.CharField(default='', max_length=200, null=True)),
                ('vender_lamination', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_record', models.CharField(default='', max_length=200, null=True)),
                ('quantity_record', models.CharField(default='', max_length=200, null=True)),
                ('unit_record', models.CharField(default='', max_length=200, null=True)),
                ('date_record', models.CharField(default='', max_length=200, null=True)),
                ('vender_record', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover_texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_texture', models.CharField(default='', max_length=200, null=True)),
                ('quantity_texture', models.CharField(default='', max_length=200, null=True)),
                ('unit_texture', models.CharField(default='', max_length=200, null=True)),
                ('date_texture', models.CharField(default='', max_length=200, null=True)),
                ('vender_texture', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
