# Generated by Django 4.2.4 on 2023-11-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0002_topi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topi_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_vendor', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_date', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_plate_no10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_quantity10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_unit10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_rate10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ord_amount10', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
