# Generated by Django 4.2.4 on 2023-11-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0004_cover_lamination_plate_lamination1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_plate_no', models.CharField(default='', max_length=200, null=True)),
                ('cutting_date', models.CharField(default='', max_length=200, null=True)),
                ('cutting_quantity', models.CharField(default='', max_length=200, null=True)),
                ('cutting_sheet_quantity', models.CharField(default='', max_length=200, null=True)),
                ('cutting_Gruce_quantity', models.CharField(default='', max_length=200, null=True)),
                ('cutting_rim_quantity', models.CharField(default='', max_length=200, null=True)),
                ('cutting_rate', models.CharField(default='', max_length=200, null=True)),
                ('cutting_amount', models.CharField(default='', max_length=200, null=True)),
                ('cutting_vendor', models.CharField(default='', max_length=200, null=True)),
                ('cutting_voucher_no', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
