# Generated by Django 5.0 on 2024-02-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0015_sale_bill_category1_sale_bill_category10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topi',
            name='t_plate_rate',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topi',
            name='t_printing_rate',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
