# Generated by Django 5.0 on 2024-02-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0017_topi_order_material_centre_topi_order_print_rate1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topi_order',
            old_name='material_centre',
            new_name='material_centre1',
        ),
    ]
