# Generated by Django 5.0 on 2024-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0018_rename_material_centre_topi_order_material_centre1'),
    ]

    operations = [
        migrations.AddField(
            model_name='topi_order',
            name='material_center',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
