# Generated by Django 5.0 on 2024-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0021_topi_order_amount_1_topi_order_amount_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topi_order',
            name='totalAmount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
