# Generated by Django 5.0 on 2024-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_app', '0024_sale_bill_brand_name1_sale_bill_brand_name10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_return',
            name='vend_category',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
