# Generated by Django 4.1.5 on 2023-01-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=200, null=True)),
                ('brand_size', models.CharField(default='', max_length=200, null=True, unique=True)),
                ('brands_added_on', models.DateTimeField(null='True')),
            ],
        ),
    ]
