# Generated by Django 4.1.5 on 2023-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0005_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='medium',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
