# Generated by Django 4.1.5 on 2023-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0006_classes_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(default='', max_length=200, null=True)),
                ('books_pages', models.CharField(default='', max_length=200, null=True)),
                ('books_cost', models.CharField(default='', max_length=200, null=True)),
                ('books_added_on', models.DateTimeField(null='True')),
            ],
        ),
    ]
