# Generated by Django 4.1.5 on 2023-01-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0007_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='subject',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
