# Generated by Django 4.1.5 on 2023-01-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0010_mediums_remove_classes_medium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='books_cost',
            new_name='books_class',
        ),
    ]
