# Generated by Django 4.1.5 on 2023-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0012_books_no_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
