# Generated by Django 4.1.5 on 2023-02-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0014_venders'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='per_book_forms',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
