# Generated by Django 4.1.3 on 2023-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0016_books_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pages_per_form',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
