# Generated by Django 4.1.3 on 2023-02-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0017_books_pages_per_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='pages_per_form',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
