# Generated by Django 4.1.3 on 2023-02-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0018_brands_pages_per_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_code',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
