# Generated by Django 4.1.3 on 2023-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0019_brands_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
