# Generated by Django 4.1.3 on 2023-02-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0020_alter_brands_brand_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='brand_code',
        ),
    ]
