# Generated by Django 4.1.3 on 2023-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0021_remove_brands_brand_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_code',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
