# Generated by Django 4.2 on 2023-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0023_brands_binding_form_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='binding_form_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
