# Generated by Django 4.2 on 2023-05-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0024_books_binding_form_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='form9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='topi',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
