# Generated by Django 4.2 on 2023-05-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0026_forms_per_kg_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='form_received_by',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='material_center',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='p_date',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='forms',
            name='p_raw_material',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='purchase_quantity',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
