# Generated by Django 4.2 on 2023-05-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0027_forms_form_received_by_forms_material_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='wastage_percent',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
