# Generated by Django 4.2 on 2023-05-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0028_forms_wastage_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='gross',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
