# Generated by Django 4.2 on 2023-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0030_material_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_centre',
            name='stock_of_cover_paper',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
