# Generated by Django 4.2 on 2023-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0031_alter_material_centre_stock_of_cover_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_centre',
            name='alias',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material_centre',
            name='group',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material_centre',
            name='print_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venders',
            name='vender_group',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
