# Generated by Django 4.2 on 2023-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0033_books_binding_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='double_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='four_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='single_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
