# Generated by Django 4.2 on 2023-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0034_forms_double_rate_forms_four_rate_forms_single_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='fourc_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='onec_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='twoc_rate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
