# Generated by Django 4.1.2 on 2023-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0036_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=200, null=True)),
                ('vender_contact', models.CharField(default='', max_length=200, null=True)),
                ('vender_email', models.CharField(default='', max_length=200, null=True)),
                ('vender_gstin_no', models.CharField(default='', max_length=200, null=True)),
                ('vender_address', models.CharField(default='', max_length=200, null=True)),
                ('vender_created_by', models.DateTimeField(null='True')),
                ('vender_group', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='extra_discount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='main_discount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
