# Generated by Django 4.1.2 on 2023-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0038_rename_vender_address_distributors_distributor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributors',
            name='distributor_created_by',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
