# Generated by Django 4.2.4 on 2023-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0041_printing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_brand_name', models.CharField(default='', max_length=200, null=True)),
                ('b_class_name', models.CharField(default='', max_length=200, null=True)),
                ('b_medium', models.CharField(default='', max_length=200, null=True)),
                ('b_subject', models.CharField(default='', max_length=200, null=True)),
                ('b_date', models.CharField(default='', max_length=200, null=True)),
                ('b_v1_name', models.CharField(default='', max_length=200, null=True)),
                ('b_m1_no', models.CharField(default='', max_length=200, null=True)),
                ('b_a1_name', models.CharField(default='', max_length=200, null=True)),
                ('total_binding', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuttting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_brand_name', models.CharField(default='', max_length=200, null=True)),
                ('c_class_name', models.CharField(default='', max_length=200, null=True)),
                ('c_medium', models.CharField(default='', max_length=200, null=True)),
                ('c_subject', models.CharField(default='', max_length=200, null=True)),
                ('c_date', models.CharField(default='', max_length=200, null=True)),
                ('c_quantity_5', models.CharField(default='', max_length=200, null=True)),
                ('c_v1_name', models.CharField(default='', max_length=200, null=True)),
                ('c_m1_no', models.CharField(default='', max_length=200, null=True)),
                ('c_a1_name', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=200, null=True)),
                ('class_name', models.CharField(default='', max_length=200, null=True)),
                ('medium', models.CharField(default='', max_length=200, null=True)),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('gather1', models.CharField(default='', max_length=200, null=True)),
                ('gather2', models.CharField(default='', max_length=200, null=True)),
                ('gather3', models.CharField(default='', max_length=200, null=True)),
                ('gather4', models.CharField(default='', max_length=200, null=True)),
                ('gather5', models.CharField(default='', max_length=200, null=True)),
                ('gather6', models.CharField(default='', max_length=200, null=True)),
                ('gather7', models.CharField(default='', max_length=200, null=True)),
                ('gather8', models.CharField(default='', max_length=200, null=True)),
                ('gather9', models.CharField(default='', max_length=200, null=True)),
                ('gather10', models.CharField(default='', max_length=200, null=True)),
                ('date', models.CharField(default='', max_length=200, null=True)),
                ('v1_name', models.CharField(default='', max_length=200, null=True)),
                ('m1_no', models.CharField(default='', max_length=200, null=True)),
                ('a1_name', models.CharField(default='', max_length=200, null=True)),
                ('total_gather', models.CharField(default='', max_length=200, null=True)),
                ('page', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_brand_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_class_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_medium1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_subject1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_striching1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_pasting1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('m_cutting1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('b_vender_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('b_mobile_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('b_adress_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('b_print_date', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
