# Generated by Django 4.2.4 on 2023-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0042_binding_cuttting_gathering_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brands_added_on_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='brands',
            name='brands_added_on',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
