# Generated by Django 4.2.4 on 2023-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0043_brands_brands_added_on_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='books_added_on_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='classes',
            name='classes_added_on_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='distributors',
            name='distributor_created_by_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='forms',
            name='forms_added_on_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='forms',
            name='p_date_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='mediums',
            name='medium_added_on_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='venders',
            name='vender_created_by_1',
            field=models.DateTimeField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='books',
            name='books_added_on',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classes_added_on',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributors',
            name='distributor_created_by',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='forms_added_on',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='p_date',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mediums',
            name='medium_added_on',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venders',
            name='vender_created_by',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
