# Generated by Django 4.2.4 on 2023-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0044_books_books_added_on_1_classes_classes_added_on_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200, null=True)),
                ('company_contact', models.CharField(default='', max_length=200, null=True)),
                ('company_email', models.CharField(default='', max_length=200, null=True)),
                ('gstin_no', models.CharField(default='', max_length=200, null=True)),
                ('company_address', models.CharField(default='', max_length=200, null=True)),
                ('company_created_by', models.CharField(default='', max_length=200, null=True)),
                ('pincode', models.CharField(default='', max_length=200, null=True)),
                ('country', models.CharField(default='', max_length=200, null=True)),
                ('state', models.CharField(default='', max_length=200, null=True)),
                ('website', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
