# Generated by Django 4.2.4 on 2023-09-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0046_bindingvender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covervender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_organization_name', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_contact', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_email', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_gstin_no', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_address', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_created_by', models.CharField(default='', max_length=200, null=True)),
                ('c_vender_group', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
