# Generated by Django 4.2.4 on 2023-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0047_covervender'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
