# Generated by Django 4.2.4 on 2023-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0048_books_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='b_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='c_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='code_g',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='m_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='p_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
