# Generated by Django 4.2.4 on 2023-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0049_binding_b_code_cuttting_c_code_gathering_code_g_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='', max_length=200, null=True)),
                ('date', models.CharField(default='', max_length=200, null=True)),
                ('voucher_no', models.CharField(default='', max_length=200, null=True)),
                ('tax_type', models.CharField(default='', max_length=200, null=True)),
                ('party', models.CharField(default='', max_length=200, null=True)),
                ('material_centre', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
