# Generated by Django 4.2.4 on 2023-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0050_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='print_approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printing',
            name='to_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='tra_from_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='voucher_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
