# Generated by Django 4.2.4 on 2023-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0051_printing_print_approved_1_printing_to_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='gather_approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gathering',
            name='to_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='tra_from_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gathering',
            name='voucher_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
