# Generated by Django 4.2.4 on 2023-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0052_gathering_gather_approved_1_gathering_to_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='binding_approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binding',
            name='to_b',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='binding',
            name='tra_from_b',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='binding',
            name='voucher_b',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
