# Generated by Django 4.2.4 on 2023-09-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0053_binding_binding_approved_1_binding_to_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttting',
            name='machine_cutting_approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='to_c',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='tra_from_c',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cuttting',
            name='voucher_c',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
