# Generated by Django 4.2.4 on 2023-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0054_cuttting_machine_cutting_approved_1_cuttting_to_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='stiching_approved_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manual',
            name='to_m',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='tra_from_m',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='voucher_m',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
