# Generated by Django 4.2.4 on 2023-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0055_manual_stiching_approved_1_manual_to_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasting_approved_1', models.BooleanField(default=False)),
                ('tra_from_pasting', models.CharField(default='', max_length=200, null=True)),
                ('to_pasting', models.CharField(default='', max_length=200, null=True)),
                ('voucher_pasting', models.CharField(default='', max_length=200, null=True)),
                ('pasting_brand_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_class_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_medium1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_subject1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_pasting1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_vender_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_mobile_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_adress_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_print_date', models.CharField(default='', max_length=200, null=True)),
                ('transfer', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
