# Generated by Django 4.2.4 on 2023-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0056_pasting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_approved_1', models.BooleanField(default=False)),
                ('tra_from_cutting', models.CharField(default='', max_length=200, null=True)),
                ('to_cutting', models.CharField(default='', max_length=200, null=True)),
                ('voucher_cutting', models.CharField(default='', max_length=200, null=True)),
                ('cutting_brand_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_class_name1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_medium1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_subject1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_cutting1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_vender_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_mobile_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_adress_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_print_date', models.CharField(default='', max_length=200, null=True)),
                ('transfer', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
