# Generated by Django 4.2.4 on 2023-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0057_manual_cutting'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='binding',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
