# Generated by Django 4.2.4 on 2023-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0058_binding_transfer_binding_transfer_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bitti_pack_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='shrink_pack_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
