# Generated by Django 4.2.4 on 2023-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0059_books_bitti_pack_size_books_shrink_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='transfer1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='transfer_pending9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
