# Generated by Django 4.2.4 on 2023-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0061_gathering_g_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='sub_brand',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
