# Generated by Django 4.2.4 on 2023-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0062_brands_sub_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
