# Generated by Django 4.2.4 on 2023-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0063_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='voucher_type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
