# Generated by Django 4.2.4 on 2023-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0065_cuttting_complete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='subbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subbrand', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
    ]
