# Generated by Django 4.2.4 on 2023-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0066_subbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(default='', max_length=200, null=True)),
                ('paper_to_be_used', models.CharField(default='', max_length=200, null=True)),
                ('width', models.CharField(default='', max_length=200, null=True)),
                ('length', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('no_of_ups', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('subject7', models.CharField(default='', max_length=200, null=True)),
                ('subject8', models.CharField(default='', max_length=200, null=True)),
                ('subject9', models.CharField(default='', max_length=200, null=True)),
                ('subject10', models.CharField(default='', max_length=200, null=True)),
                ('subject11', models.CharField(default='', max_length=200, null=True)),
                ('subject12', models.CharField(default='', max_length=200, null=True)),
                ('plate_rate', models.CharField(default='', max_length=200, null=True)),
                ('printing_rate', models.CharField(default='', max_length=200, null=True)),
                ('tax', models.CharField(default='', max_length=200, null=True)),
                ('lamination', models.CharField(default='', max_length=200, null=True)),
                ('rate1', models.CharField(default='', max_length=200, null=True)),
                ('rate2', models.CharField(default='', max_length=200, null=True)),
                ('bill_company', models.CharField(default='', max_length=200, null=True)),
                ('texture', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('subject_added_on', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
