# Generated by Django 4.2.4 on 2023-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0067_cover_printing_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbrand',
            name='brand',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subbrand',
            name='subbrand',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
