# Generated by Django 4.2.4 on 2023-10-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0068_subbrand_brand_alter_subbrand_subbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatheringvender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorganization_name1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_contact1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_email1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_gstin_no1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_address1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_created_by1', models.CharField(default='', max_length=200, null=True)),
                ('gvender_group1', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
