# Generated by Django 4.2.4 on 2023-10-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0069_gatheringvender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuttingvender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corganization_name1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_contact1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_email1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_gstin_no1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_address1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_created_by1', models.CharField(default='', max_length=200, null=True)),
                ('cvender_group1', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packingvender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porganization_name1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_contact1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_email1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_gstin_no1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_address1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_created_by1', models.CharField(default='', max_length=200, null=True)),
                ('pvender_group1', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
