# Generated by Django 4.2.4 on 2023-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0070_cuttingvender_packingvender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palte_order', models.CharField(default='', max_length=200, null=True)),
                ('subject_order', models.CharField(default='', max_length=200, null=True)),
                ('self_company', models.CharField(default='', max_length=200, null=True)),
                ('vendor_order', models.CharField(default='', max_length=200, null=True)),
                ('date_order', models.CharField(default='', max_length=200, null=True)),
                ('quantity_order', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rate_order', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='cover_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='from_vend',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='quantity_cover',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='subject13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='subject14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='subject15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='subject16',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='to_vend',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='transfer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_printing',
            name='transfer_pending',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
