# Generated by Django 4.2.4 on 2023-10-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0071_cover_order_cover_printing_cover_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='printing_rate1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
