# Generated by Django 4.2.4 on 2023-10-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0072_books_printing_rate1'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='color',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
