# Generated by Django 4.2.4 on 2023-10-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0073_books_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='gsm_paper',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
