# Generated by Django 4.2.4 on 2023-11-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0075_forms_cunit1_forms_cunit2_forms_gsm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=200, null=True)),
                ('tehsil', models.CharField(default='', max_length=200, null=True)),
                ('town', models.CharField(default='', max_length=200, null=True)),
                ('pincode', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_trade_name', models.CharField(default='', max_length=200, null=True)),
                ('brand_subtitle', models.CharField(default='', max_length=200, null=True)),
                ('class1', models.CharField(default='', max_length=200, null=True)),
                ('size', models.CharField(default='', max_length=200, null=True)),
                ('subject_name_author', models.CharField(default='', max_length=200, null=True)),
                ('code', models.CharField(default='', max_length=200, null=True)),
                ('from_size', models.CharField(default='', max_length=200, null=True)),
                ('no_of_pages', models.CharField(default='', max_length=200, null=True)),
                ('unit', models.CharField(default='', max_length=200, null=True)),
                ('no_of_forms', models.CharField(default='', max_length=200, null=True)),
                ('binding_rate', models.CharField(default='', max_length=200, null=True)),
                ('opening_stock_qty', models.CharField(default='', max_length=200, null=True)),
                ('opening_stock_value', models.CharField(default='', max_length=200, null=True)),
                ('bundle_pack', models.CharField(default='', max_length=200, null=True)),
                ('tax_information_rate', models.CharField(default='', max_length=200, null=True)),
                ('tax_information_rate_central', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=200, null=True)),
                ('alias', models.CharField(default='', max_length=200, null=True)),
                ('primary_input', models.CharField(default='', max_length=200, null=True)),
                ('type', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(default='', max_length=200, null=True)),
                ('t_series', models.CharField(default='', max_length=200, null=True)),
                ('vehno', models.CharField(default='', max_length=200, null=True)),
                ('delivered_at', models.CharField(default='', max_length=200, null=True)),
                ('narration', models.CharField(default='', max_length=200, null=True)),
                ('roll_quantity', models.CharField(default='', max_length=200, null=True)),
                ('roll_unit', models.CharField(default='', max_length=200, null=True)),
                ('roll_rate', models.CharField(default='', max_length=200, null=True)),
                ('roll_amount', models.CharField(default='', max_length=200, null=True)),
                ('paper_rim_qty', models.CharField(default='', max_length=200, null=True)),
                ('rim_unit', models.CharField(default='', max_length=200, null=True)),
                ('rim_rate', models.CharField(default='', max_length=200, null=True)),
                ('rim_amount', models.CharField(default='', max_length=200, null=True)),
                ('cover_paper_qty', models.CharField(default='', max_length=200, null=True)),
                ('cover_paper_unit', models.CharField(default='', max_length=200, null=True)),
                ('cover_paper_rate', models.CharField(default='', max_length=200, null=True)),
                ('cover_paper_amount', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
