# Generated by Django 4.2.4 on 2023-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0076_database_item_creation_main_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binder_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('prefix', models.CharField(default='', max_length=200, null=True)),
                ('alias', models.CharField(default='', max_length=200, null=True)),
                ('adress', models.CharField(default='', max_length=200, null=True)),
                ('contact_no', models.CharField(default='', max_length=200, null=True)),
                ('whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(default='', max_length=200, null=True)),
                ('cust_prefix', models.CharField(default='', max_length=200, null=True)),
                ('cust_alias', models.CharField(default='', max_length=200, null=True)),
                ('cust_adress', models.CharField(default='', max_length=200, null=True)),
                ('cust_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('cust_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('cust_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('zone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tour_group', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cust_eamil', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tahsil', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('group', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('price_category', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cutter_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=200, null=True)),
                ('c_prefix', models.CharField(default='', max_length=200, null=True)),
                ('c_alias', models.CharField(default='', max_length=200, null=True)),
                ('c_adress', models.CharField(default='', max_length=200, null=True)),
                ('c_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('c_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('c_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cutting_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gather_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='', max_length=200, null=True)),
                ('g_prefix', models.CharField(default='', max_length=200, null=True)),
                ('g_alias', models.CharField(default='', max_length=200, null=True)),
                ('g_adress', models.CharField(default='', max_length=200, null=True)),
                ('g_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('g_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('g_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gathering_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='General_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default='', max_length=200, null=True)),
                ('g_prefix', models.CharField(default='', max_length=200, null=True)),
                ('g_alias', models.CharField(default='', max_length=200, null=True)),
                ('g_adress', models.CharField(default='', max_length=200, null=True)),
                ('g_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('g_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('g_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('previous_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('act_material_center', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('fax', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('eamil', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tel_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('print_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('group', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(default='', max_length=200, null=True)),
                ('m_prefix', models.CharField(default='', max_length=200, null=True)),
                ('m_alias', models.CharField(default='', max_length=200, null=True)),
                ('m_adress', models.CharField(default='', max_length=200, null=True)),
                ('m_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('m_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('m_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('machine_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packer_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(default='', max_length=200, null=True)),
                ('pack_prefix', models.CharField(default='', max_length=200, null=True)),
                ('pack_alias', models.CharField(default='', max_length=200, null=True)),
                ('pack_adress', models.CharField(default='', max_length=200, null=True)),
                ('pack_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('pack_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('pack_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('packing_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bitti_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paster_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=200, null=True)),
                ('p_prefix', models.CharField(default='', max_length=200, null=True)),
                ('p_alias', models.CharField(default='', max_length=200, null=True)),
                ('p_adress', models.CharField(default='', max_length=200, null=True)),
                ('p_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('p_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('p_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pasting_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stitcher_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=200, null=True)),
                ('s_prefix', models.CharField(default='', max_length=200, null=True)),
                ('s_alias', models.CharField(default='', max_length=200, null=True)),
                ('s_adress', models.CharField(default='', max_length=200, null=True)),
                ('s_contact_no', models.CharField(default='', max_length=200, null=True)),
                ('s_whatsapp', models.CharField(default='', max_length=200, null=True)),
                ('s_opening_balence', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stitching_rate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='database',
            old_name='district',
            new_name='district_d',
        ),
    ]
