# Generated by Django 4.2.4 on 2023-11-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0077_binder_ledger_customer_ledger_cutter_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='currency',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='tour_group',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='zone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
