# Generated by Django 4.2.4 on 2023-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0078_database_currency_database_tour_group_database_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ledger',
            name='code',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
