# Generated by Django 4.2.4 on 2023-11-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0079_customer_ledger_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_operation',
            name='party',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
