# Generated by Django 4.2.4 on 2023-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0080_transaction_operation_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_order',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
