# Generated by Django 4.2.4 on 2023-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0081_cover_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='cover_scrap_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_date', models.CharField(default='', max_length=200, null=True)),
                ('cover_voucher_no', models.CharField(default='', max_length=200, null=True)),
                ('cover_subject', models.CharField(default='', max_length=200, null=True)),
                ('cover_qty', models.CharField(default='', max_length=200, null=True)),
                ('cover_unit', models.CharField(default='', max_length=200, null=True)),
                ('cover_rate', models.CharField(default='', max_length=200, null=True)),
                ('cover_bill_material', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_bill_material_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_alias', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_item_produce', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_quantity', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_unit1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cover_expenses', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item_generated', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('item_consumed', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='other_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contes', models.CharField(default='', max_length=200, null=True)),
                ('account_dr', models.CharField(default='', max_length=200, null=True)),
                ('account_cr', models.CharField(default='', max_length=200, null=True)),
                ('Debit_credit', models.CharField(default='', max_length=200, null=True)),
                ('account', models.CharField(default='', max_length=200, null=True)),
                ('debit', models.CharField(default='', max_length=200, null=True)),
                ('credit', models.CharField(default='', max_length=200, null=True)),
                ('inst_type', models.CharField(default='', max_length=200, null=True)),
                ('inst_no', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
