# Generated by Django 4.2.4 on 2023-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0088_product_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_creation',
            name='binding_no_of_form',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item_creation',
            name='item_binding_form_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
