# Generated by Django 4.2.4 on 2023-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0089_item_creation_binding_no_of_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Printing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_pages', models.CharField(default='', max_length=200, null=True)),
                ('form_vender', models.CharField(default='', max_length=200, null=True)),
                ('form_code', models.CharField(default='', max_length=200, null=True)),
                ('form_brand', models.CharField(default='', max_length=200, null=True)),
                ('form_class', models.CharField(default='', max_length=200, null=True)),
                ('form_medium', models.CharField(default='', max_length=200, null=True)),
                ('form_subject', models.CharField(default='', max_length=200, null=True)),
                ('form_quantity', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form1', models.CharField(default='', max_length=200, null=True)),
                ('form2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form4', models.CharField(default='', max_length=200, null=True)),
                ('form5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form7', models.CharField(default='', max_length=200, null=True)),
                ('form8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer_8', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer9', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transfer10', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('form_date', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('total_forms', models.CharField(default='', max_length=200, null=True)),
                ('transfer', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending1', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending2', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending3', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending4', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending5', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending6', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending7', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending8', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending9', models.CharField(default='', max_length=200, null=True)),
                ('transfer_pending10', models.CharField(default='', max_length=200, null=True)),
                ('to', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
