# Generated by Django 4.2.4 on 2023-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0091_cover_order_amount1_cover_order_amount10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_by',
            name='punit22',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product_by',
            name='punit33',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
