# Generated by Django 4.2.4 on 2023-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0094_forms_opening_stock_rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder_ledger',
            name='debit_binder',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_ledger',
            name='debit_customer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cutter_ledger',
            name='debit_cutter',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gather_ledger',
            name='debit_gather',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='general_ledger',
            name='debit_general',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machine_ledger',
            name='debit_machine',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packer_ledger',
            name='debit_packer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paster_ledger',
            name='debit_paster',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stitcher_ledger',
            name='debit_stitcher',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
