# Generated by Django 4.2.4 on 2023-12-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0096_cutter_ledger_cutting_rate_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='Waste',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='waste_percent',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
