# Generated by Django 4.2.4 on 2023-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0099_binder_ledger_email_binder_ledger_vender_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='account',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='account9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='credit9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='dc9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='debit9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration11',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration12',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration13',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration14',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration15',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='short_narration9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
