# Generated by Django 5.0 on 2023-12-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0102_subbrand_additionaldiscount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbrand',
            name='subtitle',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
