# Generated by Django 5.0 on 2023-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0104_forms_cunit3_forms_cunit4_forms_raw_material_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='printing_form_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
