# Generated by Django 5.0 on 2023-12-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0105_books_printing_form_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_operation',
            old_name='Particular1',
            new_name='Particular',
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='Particular_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='dynamic_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='ex_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='ex_no_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='p_weight',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='p_weight_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='rim',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='rim_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='roll_amount_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='roll_quantity_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='roll_rate_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='roll_unit_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='sheet',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='sheet_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='weight',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction_operation',
            name='weight_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
