# Generated by Django 5.0 on 2023-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0106_rename_particular1_transaction_operation_particular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=200, null=True)),
                ('item_alias', models.CharField(default='', max_length=200, null=True)),
                ('item_print_name', models.CharField(default='', max_length=200, null=True)),
                ('item_group', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
