# Generated by Django 5.0 on 2024-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0108_subbrand_binding_form_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='subbrand_binding_form_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='subbrand_printing_form_size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
