# Generated by Django 5.0 on 2024-01-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0109_books_subbrand_binding_form_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_master', models.CharField(default='', max_length=200, null=True)),
                ('tehsil_master', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
