# Generated by Django 5.0 on 2024-01-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0110_district1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='conversion_factor1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='conversion_factor2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='conversion_unit1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='conversion_unit2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='opening_stock1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='opening_stock2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='opening_unit1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='opening_unit2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='unit4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
