# Generated by Django 5.0 on 2024-01-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0111_cover_rawmaterial_conversion_factor1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='conversion_factor1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='opening_stock1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
