# Generated by Django 5.0 on 2024-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0112_forms_conversion_factor1_forms_opening_stock1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='', max_length=200, null=True)),
                ('tour_group', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
