# Generated by Django 5.0 on 2024-01-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0113_tour_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='extra_discount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='main_discount',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='selling_price',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
