# Generated by Django 5.0 on 2024-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0114_books_extra_discount_books_main_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='Cover_rawmaterial',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
