# Generated by Django 5.0 on 2024-01-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0115_cover_rawmaterial_cover_rawmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover_rawmaterial',
            old_name='Cover_rawmaterial',
            new_name='Cover_material_centre',
        ),
    ]
