# Generated by Django 5.0 on 2024-01-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0116_rename_cover_rawmaterial_cover_rawmaterial_cover_material_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_rawmaterial',
            name='cover_material',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
