# Generated by Django 5.0 on 2024-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0121_pasting_material_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttting',
            name='Material_center',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
