# Generated by Django 5.0 on 2024-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0122_cuttting_material_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='Material_center',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
