# Generated by Django 5.0 on 2024-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0123_printing_material_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbrand',
            name='brand_combine',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
