# Generated by Django 5.0 on 2024-02-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0126_cover_order_material_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular10',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular8',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_particular9',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty10',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty8',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_qty9',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate10',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate8',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_rate9',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_total_quantity',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit10',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit8',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='cover_scrap_unit9',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover10',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover3',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover4',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover5',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover6',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover7',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover8',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_scrap_voucher',
            name='remaning_cover9',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
