# Generated by Django 5.0 on 2024-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_app', '0129_cover_order_lamination_sheet1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover_order',
            name='lamination_sheet',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_order',
            name='printing_sheet',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cover_order',
            name='texture_sheet',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
